# Generated by Django 4.2.8 on 2024-01-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'product': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')}, to='store.variation'),
        ),
    ]
